from fastapi import APIRouter, Query, File, UploadFile, HTTPException

from sqlalchemy import Boolean, Column, ForeignKey, Integer, String, PrimaryKeyConstraint
from sqlalchemy import create_engine, Column, Integer, String, ForeignKey, UniqueConstraint
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session


# Create the base model for SQLAlchemy
Base = declarative_base()

def initialize_rdbs():
    # Create the SQLAlchemy engine and session
   # Create a connection to the MySQL server without specifying a database
    DATABASE_URL = "mysql+pymysql://root@localhost/citidream"
    engine = create_engine(DATABASE_URL, echo=True)

    # Create a connection to the MySQL server without specifying a database
    connection = engine.connect()

    # Close the connection to the MySQL server
    connection.close()

    Base.metadata.create_all(bind=engine)

    SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    session = SessionLocal()

    return session

def insert_dummy_data(session):

    # Insert data into Object_Table
    object1 = Object_Table(ObjectID='1', ObjectName='Object 1', Department='Dept 1', ExcerptID='1')
    object2 = Object_Table(ObjectID='2', ObjectName='Object 2', Department='Dept 2', ExcerptID='2')
    object3 = Object_Table(ObjectID='3', ObjectName='Object 3', Department='Dept 1', ExcerptID='3')

    # Insert data into ObjectVotes
    vote1 = ObjectVotes(ObjectID='1', Upvotes=5, Downvotes=2)
    vote2 = ObjectVotes(ObjectID='2', Upvotes=10, Downvotes=1)
    vote3 = ObjectVotes(ObjectID='3', Upvotes=3, Downvotes=0)

    session.add_all([object1, object2, object3, vote1, vote2, vote3])
    session.commit()
    session.close()


class Object_Table(Base):
    """
    This table stores
        - ObjectID: This ID refers to the ID of the object in S3
        - ObjectName: This is the name of the object, usually filename
        - Department: This is the department that the object belongs to, if None it belongs to all departments
        - ExcerptID: This ID refers to the ID of the excerpt generated by LLM, an object can have many excerpts.

    The composite primary key is ObjectID and ExcerptID
    """
    __tablename__ = "ObjectTable"

    ObjectID = Column(String(64))
    ObjectName = Column(String(255))
    Department = Column(String(128))
    ExcerptID = Column(String(64))

    __table_args__ = (
        PrimaryKeyConstraint('ObjectID', 'ExcerptID'),
    )

class ObjectVotes(Base):
    """
    This table stores
        - ObjectID: This ID refers to the ID of the object in S3
        - Upvotes: This is the number of upvotes that the object has
        - Downvotes: This is the number of downvotes that the object has
    """

    __tablename__ = "ObjectVotes"

    ObjectID = Column(String(64))
    Upvotes = Column(Integer, default=0)
    Downvotes = Column(Integer, default=0)


    __table_args__ = (
        PrimaryKeyConstraint('ObjectID'),
    )
